[package]
name = "typst-2-rsx"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
dioxus = "0.6.2"
serde ={ version = "1.0.217", features = ["derive"]}
serde-xml-rs = "0.6.0"
serde_json = "1.0.137"
